// deno test --allow-env supabase/functions/_shared/engine_life_test.ts
//
// E-M3 "the Life" wiring (CONTRACTS §15): newsRead's lens walk + gates,
// practice's three modes, practiceReview's digest gate, and the digest
// builder itself.
import { assert, assertEquals } from "jsr:@std/assert@1";
import {
  applyStateOps,
  type CourseUnit,
  initialState,
  instructionBlock,
  KIND_REGISTRY,
} from "./engine.ts";
import {
  buildPracticeDigest,
  EXAMEN_QUESTIONS,
  type NewsReadSpec,
  type PracticeSpec,
} from "./kinds_life.ts";

const unit: CourseUnit = { number: 0, title: "", reading: [] };

const newsSpec: NewsReadSpec = {
  brief: {
    headline: "City weighs an AI witness in court",
    summary: "A municipal court is deciding whether transcripts generated by an AI system may be entered as testimony.",
    question: "Can testimony without a testifier carry epistemic weight?",
    domain: "epistemology",
    sourceUrls: ["https://example.org/a"],
    lensPairId: "lens-epistemology-1",
    lensPair: {
      id: "lens-epistemology-1",
      domain: "epistemology",
      a: { name: "Empiricism", ontologyId: "epistemology.empiricism", oneLiner: "trust tracks observation" },
      b: { name: "Rationalism", ontologyId: "epistemology.rationalism", oneLiner: "trust tracks justification" },
      splitHint: "whether reliability without understanding is enough",
    },
  },
};

Deno.test("life kinds are registered with canComplete guards", () => {
  for (const kind of ["newsRead", "practice", "practiceReview"] as const) {
    assert(KIND_REGISTRY[kind], `${kind} missing from KIND_REGISTRY`);
    assert(typeof KIND_REGISTRY[kind].canComplete === "function");
  }
});

Deno.test("newsRead: lens walk, completion gated on position (§15.2)", () => {
  let state = initialState("newsRead", unit, { spec: newsSpec });
  assertEquals(state.phase, "brief");

  // Complete from brief is refused.
  let r = applyStateOps("newsRead", state, [{ op: "completeSession" }]);
  assertEquals(r.completeSession, false);
  assertEquals(r.completionRefused, true);

  for (const expected of ["lensA", "lensB", "split", "position"]) {
    r = applyStateOps("newsRead", r.state, [{ op: "advancePhase" }]);
    assertEquals(r.state.phase, expected);
  }
  r = applyStateOps("newsRead", r.state, [{ op: "completeSession" }]);
  assert(r.completeSession);

  // Both lenses and the no-aggregates rule live in the instruction.
  const block = instructionBlock("newsRead", state, { unit, pace: "standard", spec: newsSpec });
  assert(block.includes("Empiricism") && block.includes("Rationalism"));
  assert(block.includes("NEVER present crowd numbers"));
  assert(block.includes("EVEN-HANDED BY CONSTRUCTION"));
});

Deno.test("practice: evening examen counts three questions before completing (§15.3)", () => {
  const spec: PracticeSpec = {
    mode: "evening",
    exercise: { id: "examen", questions: [...EXAMEN_QUESTIONS] },
  };
  let state = initialState("practice", unit, { spec });
  assertEquals(state.mode, "evening");
  assertEquals(state.step, 0);

  let r = applyStateOps("practice", state, [{ op: "completeSession" }]);
  assertEquals(r.completionRefused, true);

  for (let i = 1; i <= 3; i++) {
    r = applyStateOps("practice", (r ?? { state }).state, [{ op: "advancePhase" }]);
    assertEquals(r.state.step, i);
  }
  r = applyStateOps("practice", r.state, [{ op: "completeSession" }]);
  assert(r.completeSession);

  const block = instructionBlock("practice", r.state, { unit, pace: "standard", spec });
  assert(block.includes("never about the student's worth") || block.includes("never about the self's worth"));
  assert(block.includes("TRAINING, not therapy"));
});

Deno.test("practice: morning carries the two-beat contract; visualization gates on 2 steps", () => {
  const mSpec: PracticeSpec = {
    mode: "morning",
    exercise: { id: "mp-001", prompt: "What is the one thing today that is yours to control?" },
  };
  const mState = initialState("practice", unit, { spec: mSpec });
  const mBlock = instructionBlock("practice", mState, { unit, pace: "standard", spec: mSpec });
  assert(mBlock.includes("TWO beats"));
  assert(mBlock.includes("80 words"));
  assert(KIND_REGISTRY.practice.canComplete!(mState)); // server force-completes post-opening

  const vSpec: PracticeSpec = {
    mode: "visualization",
    exercise: { id: "nv-001", title: "The Borrowed Cup", exercise: "…", debrief: "…" },
  };
  let state = initialState("practice", unit, { spec: vSpec });
  assertEquals(KIND_REGISTRY.practice.canComplete!(state), false);
  let r = applyStateOps("practice", state, [{ op: "advancePhase" }]);
  r = applyStateOps("practice", r.state, [{ op: "advancePhase" }]);
  assert(KIND_REGISTRY.practice.canComplete!(r.state));
});

Deno.test("practiceReview: reflection gate + digest-aware instruction (§15.3)", () => {
  let state = initialState("practiceReview", unit, {});
  assertEquals(state.phase, "review");

  let r = applyStateOps("practiceReview", state, [{ op: "completeSession" }]);
  assertEquals(r.completionRefused, true);

  const withDigest = instructionBlock("practiceReview", state, {
    unit,
    pace: "standard",
    practiceDigestPresent: true,
  });
  assert(withDigest.includes("practice digest"));
  const without = instructionBlock("practiceReview", state, { unit, pace: "standard" });
  assert(without.includes("no entries this week"));

  r = applyStateOps("practiceReview", state, [{ op: "advancePhase" }]);
  assertEquals(r.state.phase, "reflection");
  r = applyStateOps("practiceReview", r.state, [{ op: "completeSession" }]);
  assert(r.completeSession);
});

Deno.test("buildPracticeDigest: caps, truncates, nulls on empty", () => {
  assertEquals(buildPracticeDigest([]), null);
  const digest = buildPracticeDigest([
    { mode: "morning", entry: "Hold my temper in the standup.", local_date: "2026-07-11" },
    { mode: "evening", entry: "x".repeat(300), local_date: "2026-07-10" },
  ])!;
  assert(digest.startsWith("PRACTICE DIGEST"));
  assert(digest.includes("[morning] Hold my temper"));
  assert(digest.includes("…"), "long entries truncate");
  assert(!digest.includes("x".repeat(200)));
});
